### ISSUE TITLE
Sticky header

### ISSUE THREAD

**Issue by kstawinski** [kstawinski/emojis#5]
Create sticky header or show if scroll up

**Comment by DasneiN** [comment]
Hello!
Here is PR with sticky header implementation: [https://github.com/kstawinski/emojis/pull/14](https://github.com/kstawinski/emojis/pull/14)
Check it, plz 😉

**Comment by kstawinski** [comment]
Hi @DasneiN!
Everything looks good, your PR was merged. Thanks ❤️
